#pragma once

namespace orm {

enum ELanguage { kLangEN = 0, kLangZH, kNumLanguages };
int DetectSystemLanguage();

inline int &UILang() {
  static int lang = DetectSystemLanguage();
  return lang;
}

enum EText {
  kTxtRelease,
  kTxtRange,
  kTxtAttack,
  kTxtRes,
  kTxtUndo,
  kTxtRedo,
  kTxtSave,
  kTxtLoad,
  kTxtLanguage,
  kTxtDark,
  kTxtLight,
  kTxtThemeColor,
  kTxtSettings,
  kTxtTheme,
  kTxtHue,
  kTxtSaturation,
  kTxtSatNone,
  kTxtSatLow,
  kTxtSatMed,
  kTxtSatHigh,
  kTxtChinese,
  kTxtTipRelease,
  kTxtTipReleaseMode,
  kTxtTipRange,
  kTxtTipAttack,
  kTxtTipRes,
  kTxtTipLfRes,
  kTxtTipMode,
  kTxtAudio,
  kTxtAudioInput,
  kTxtAudioOutput,
  kTxtDriver,
  kTxtTipChanMode,
  kTxtTipMergeAlgo,
  kTxtLevelHold,
  kTxtReset,
  kTxtTipLevelMode,
  kTxtTipLevelHold,
  kTxtTipReset,
  kTxtLfLow,
  kTxtLfMid,
  kTxtLfHigh,
  kTxtFreeze,
  kTxtTipFreeze,
  kTxtDeveloper,
  kTxtTestSignal,
  kTxtGenFreq,
  kTxtGenLevel,
  kTxtGenRestart,
  kTxtGenReseed,
  kTxtGenToOutput,
  kTxtGenHold,
  kTxtTipLevelHoldTime,
  kTxtTipSlope,
  kTxtTipWindow,
  kTxtWinSharp,
  kTxtWinClean,
  kTxtWinBH5,
  kTxtTipRtaOctave,
  kTxtTipVQTGamma,
  kTxtLoudMomentary,  // 响度计: 瞬时响度 (M, 400ms)
  kTxtLoudShort,      // 响度计: 短时响度 (S, 3s)
  kTxtLoudInt,        // 响度计: 综合响度 (I, 双门限累计)
  kTxtLoudLra,        // 响度计: 响度范围 (LRA)
  kTxtLoudTp,         // 响度计: 真峰值
  kTxtLoudTarget,     // 响度计: 目标
  kTxtTipLoudPreset,  // 响度计: 目标预设 tooltip
  kTxtTipLoudReset,   // 响度计: RESET tooltip
  kNumTexts
};

inline const char *Tr(int id, int lang) {
  static const char *const kTable[kNumLanguages][kNumTexts] = {
      {
          "RELEASE",
          "RANGE",
          "ATTACK",
          "RES",
          "UNDO",
          "REDO",
          "SAVE",
          "LOAD",
          "LANGUAGE",
          "DARK",
          "LIGHT",
          "Theme Color",
          "SETTINGS",
          "THEME",
          "Hue",
          "Saturation",
          "NONE",
          "LOW",
          "MED",
          "HIGH",
          "中文",
          "Spectrum display release time (dB-domain fall, 0.05-2 s)",
          "Release fall mode: LOG = dB-domain one-pole (slows near signal), UNIF = uniform dB/s fall (constant speed)",
          "Spectrum display bottom: click to cycle 80 / 100 / 120 dB",
          "Spectrum display attack time",
          "Spectrum analysis FFT size (LOW/MID/HIGH: 2048/4096/8192)",
          "PBT low-frequency resolution (40/20/10 Hz)",
          "Switch analysis engine (STFT / VQT / PBT / RTA)",
          "AUDIO",
          "Input",
          "Output",
          "Driver",
          "Channel display: PWR (merge, total power) / L/R stereo / SUM (merge, mono sum)",
          "Merge algorithm (PWR: Total Power, SUM: Mono Sum)",
          "HOLD",
          "RESET",
          "Meter mode: dBTP (true peak, ITU-R BS.1770) / dBFS + RMS / VU (0 VU = -18 dBFS)",
          "Peak hold on/off (spectrum hold curve and meter hold line)",
          "Clear peak hold and overload latch",
          "LOW",
          "MID",
          "HIGH",
          "FREEZE",
          "Freeze display: hold current picture; switching engine re-analyzes the same frozen audio with the new algorithm",
          "DEVELOPER",
          "Signal",
          "Frequency",
          "Level",
          "RESTART",
          "RESEED",
          "TO OUTPUT",
          "HOLD",
          "Peak hold duration: click to cycle 0.5s / 2s / ∞ (infinite hold)",
          "Spectrum slope (dB/oct, pivot ~632 Hz): STFT 0/3/4.5, VQT/PBT/RTA -3/0/1.5; each engine keeps its own value",
          "Window mode (STFT and VQT each keep their own value): SHARP (Hann: sharp mainlobe, classic response) / CLEAN (4-term Blackman-Harris: -92 dB ultra-low leakage) / BH5 (5-term Blackman-Harris: -125 dB ultra-low leakage, slightly wider mainlobe)",
          "SHARP",
          "CLEAN",
          "BH5",
          "RTA fractional-octave resolution (LOW/MID/HIGH = 1/6/1/12/1/24: 59/118/236 bands)",
          "VQT low-frequency bandwidth floor gamma (Hz): band width = fc/Q + gamma — higher = wider low bands, faster response; lower = sharper",
          "MOMENTARY",
          "SHORT-TERM",
          "INTEGRATED",
          "LRA",
          "TRUE PEAK",
          "TARGET",
          "Loudness target preset: -14 (streaming music) / -16 (Apple Music) / -23 (EBU R128 broadcast)",
          "Reset integrated loudness, LRA and true peak hold",
      },
      {
          "释放",
          "范围",
          "起音",
          "分辨率",
          "撤销",
          "重做",
          "保存",
          "读取",
          "语言",
          "深色",
          "浅色",
          "主题色",
          "设置",
          "主题",
          "色相",
          "饱和度",
          "无",
          "低",
          "中",
          "高",
          "中文",
          "频谱显示释放时间（对数域回落，0.05–2 秒）",
          "释放回落模式：对数 = dB 域单极点（接近信号时渐缓），匀速 = 恒定 dB/s 速率下落",
          "频谱显示范围：点击循环切换底部 80 / 100 / 120 dB",
          "频谱显示上升时间",
          "频谱分析 FFT 尺寸（低/中/高: 2048/4096/8192）",
          "PBT 低频分辨率（40/20/10 Hz）",
          "切换分析引擎（STFT / VQT / PBT / RTA）",
          "音频",
          "输入",
          "输出",
          "驱动",
          "声道显示：PWR（合并，总功率和）/ L/R 立体声 / SUM（合并，单声道求和）",
          "合并算法（PWR: 总功率和, SUM: 单声道求和）",
          "保持",
          "重置",
          "电平表模式：dBTP 真峰值（ITU-R BS.1770）/ dBFS+RMS / VU（0 VU = -18 dBFS）",
          "峰值保持开关（频谱保持曲线与电平表保持亮线）",
          "清除峰值保持与过载锁存",
          "低",
          "中",
          "高",
          "冻结",
          "冻结显示：定格当前画面；冻结中切换引擎时，用新算法重新分析同一段冻结音频",
          "开发者",
          "测试信号",
          "频率",
          "电平",
          "重开",
          "换种子",
          "送到输出",
          "锁相位",
          "峰值保持时长：点击循环切换 0.5s / 2s / ∞（无限保持）",
          "频谱斜率（dB/oct，支点约 632 Hz）：STFT 0/3/4.5，VQT/PBT/RTA -3/0/1.5；各引擎独立保存",
          "窗函数模式（STFT 与 VQT 独立保存档位）：锐利（Hann: 锐利窄主瓣，经典响应）/ 纯净（4阶 Blackman-Harris: -92 dB 极低旁瓣泄露）/ BH5（5阶 Blackman-Harris: -125 dB 超低泄露，主瓣略宽）",
          "锐利",
          "纯净",
          "BH5",
          "RTA 分数倍频程分辨率（LOW/MID/HIGH = 1/6/1/12/1/24：59/118/236 带）",
          "VQT 低频带宽下限 γ（Hz）：带宽 = fc/Q + γ —— 越大低频带越宽、响应越快；越小越锐利",
          "瞬时",
          "短时",
          "总响度",
          "LRA",
          "真峰值",
          "目标",
          "响度目标预设：-14（流媒体音乐）/ -16（Apple Music）/ -23（EBU R128 广播）",
          "重置综合响度、LRA 与真峰值锁存",
      },
  };
  return kTable[lang][id];
}

} // namespace orm
