#pragma once

namespace orm {

enum ELanguage { kLangEN = 0, kLangZH, kNumLanguages };
int DetectSystemLanguage();

inline int &UILang() {
  static int lang = DetectSystemLanguage();
  return lang;
}

enum EText {
  kTxtRelease,
  kTxtRange,
  kTxtAttack,
  kTxtRes,
  kTxtUndo,
  kTxtRedo,
  kTxtSave,
  kTxtLoad,
  kTxtLanguage,
  kTxtDark,
  kTxtLight,
  kTxtThemeColor,
  kTxtSettings,
  kTxtTheme,
  kTxtHue,
  kTxtSaturation,
  kTxtSatNone,
  kTxtSatLow,
  kTxtSatMed,
  kTxtSatHigh,
  kTxtChinese,
  kTxtTipRelease,
  kTxtTipReleaseMode,
  kTxtTipRange,
  kTxtTipAttack,
  kTxtTipRes,
  kTxtTipLfRes,
  kTxtTipMode,
  kTxtAudio,
  kTxtAudioInput,
  kTxtAudioOutput,
  kTxtDriver,
  kTxtTipChanMode,
  kTxtTipMergeAlgo,
  kTxtChanLR,      // 声道显示模式按钮: 立体声 (L/R)
  kTxtChanPWR,     // 声道显示模式按钮: 能量和 (左右能量合并)
  kTxtChanSUM,     // 声道显示模式按钮: 信号和 (左右信号直接相加)
  kTxtRelLog,      // 释放回落模式按钮: 对数 (LOG, dB 域单极点)
  kTxtRelLin,      // 释放回落模式按钮: 线性 (LIN, 恒定 dB/s 速率)
  kTxtLevelHold,
  kTxtReset,
  kTxtTipLevelMode,
  kTxtTipLevelHold,
  kTxtTipReset,
  kTxtLfLow,
  kTxtLfMid,
  kTxtLfHigh,
  kTxtFreeze,
  kTxtTipFreeze,
  kTxtDeveloper,
  kTxtTestSignal,
  kTxtGenFreq,
  kTxtGenLevel,
  kTxtGenRestart,
  kTxtGenReseed,
  kTxtGenToOutput,
  kTxtGenHold,
  kTxtTipLevelHoldTime,
  kTxtTipSlope,
  kTxtTipWindow,
  kTxtWinSharp,
  kTxtWinClean,
  kTxtTipRtaOctave,
  kTxtTipVQTGamma,
  kTxtLoudMomentary,  // 响度计: 瞬时响度 (M, 400ms)
  kTxtLoudShort,      // 响度计: 短时响度 (S, 3s)
  kTxtLoudInt,        // 响度计: 综合响度 (I, 双门限累计)
  kTxtLoudLra,        // 响度计: 响度范围 (LRA)
  kTxtLoudTp,         // 响度计: 真峰值
  kTxtLoudTarget,     // 响度计: 目标
  kTxtTipLoudPreset,  // 响度计: 目标预设 tooltip
  kTxtTipLoudReset,   // 响度计: RESET tooltip
  kTxtSpeedMin,       // 频谱速度预设按钮: 最慢 (MIN, 释放 4s)
  kTxtSpeedSlow,      // 频谱速度预设按钮: 慢速 (SLOW, 释放 2s)
  kTxtSpeedMed,       // 频谱速度预设按钮: 中速 (MED, 释放 1s)
  kTxtSpeedFast,      // 频谱速度预设按钮: 快速 (FAST, 释放 0.5s)
  kTxtSpeedMax,       // 频谱速度预设按钮: 最快 (MAX, 释放 0.2s)
  kTxtTipSpeed,       // 频谱速度预设 tooltip
  kTxtScopeTitle,     // 声像显示面板标题
  kTxtScopeCorr,      // 声像读数: 相关性
  kTxtScopeWidth,     // 声像读数: 宽度
  kTxtScopeBalance,   // 声像读数: 平衡
  kTxtScopeAnti,      // 声像: 反相角标
  kTxtTipScopeRange,  // 声像显示范围 tooltip
  kNumTexts
};

inline const char *Tr(int id, int lang) {
  static const char *const kTable[kNumLanguages][kNumTexts] = {
      {
          "RELEASE",
          "RANGE",
          "ATTACK",
          "RES",
          "UNDO",
          "REDO",
          "SAVE",
          "LOAD",
          "LANGUAGE",
          "DARK",
          "LIGHT",
          "Theme Color",
          "SETTINGS",
          "THEME",
          "Hue",
          "Saturation",
          "NONE",
          "LOW",
          "MED",
          "HIGH",
          "中文",
          "Spectrum display release time (dB-domain fall, 0.05-2 s)",
          "Release fall mode: LOG = dB-domain one-pole (slows near signal), LIN = linear dB/s fall (constant speed)",
          "Spectrum display bottom: click to cycle 80 / 100 / 120 dB",
          "Spectrum display attack time",
          "Spectrum analysis FFT size (L/M/H: 2048/4096/8192)",
          "PBT low-frequency resolution (L/M/H: 40/20/10 Hz, smaller = finer)",
          "Switch analysis engine (STFT / VQT / PBT / RTA)",
          "AUDIO",
          "Input",
          "Output",
          "Driver",
          "Channel display: PWR (merge, total power) / L/R stereo / SUM (merge, mono sum)",
          "Merge algorithm (PWR: Total Power, SUM: Mono Sum)",
          "L/R",
          "PWR",
          "SUM",
          "LOG",
          "LIN",
          "HOLD",
          "RESET",
          "Meter mode: dBTP (true peak, ITU-R BS.1770) / dBFS + RMS (VU meter is always shown separately)",
          "Peak hold on/off (spectrum hold curve and meter hold line)",
          "Reset everything: meter hold / overload / persistent true peak / loudness (I, LRA, true peak)",
          "L",
          "M",
          "H",
          "FREEZE",
          "Freeze display: hold current picture; switching engine re-analyzes the same frozen audio with the new algorithm",
          "DEVELOPER",
          "Signal",
          "Frequency",
          "Level",
          "RESTART",
          "RESEED",
          "TO OUTPUT",
          "HOLD",
          "Peak hold duration: click to cycle 0.5s / 2s / ∞ (infinite hold)",
          "Spectrum slope (dB/oct, pivot ~632 Hz): STFT 0/3/4.5, VQT/PBT/RTA -3/0/1.5; each engine keeps its own value",
          "Window mode (STFT and VQT each keep their own value): SHARP (Hann: sharp mainlobe, classic response) / CLEAN (5-term Blackman-Harris: -125 dB ultra-low leakage, slightly wider mainlobe)",
          "SHARP",
          "CLEAN",
          "RTA fractional-octave resolution (L/M/H = 1/6/1/12/1/24: 59/118/236 bands)",
          "VQT low-frequency bandwidth floor gamma (L/M/H = 20/10/5 Hz): band width = fc/Q + gamma — H = narrowest low bands, finest low-frequency resolution; L = wider low bands, faster response",
          "MOMENTARY",
          "SHORT-TERM",
          "INTEGRATED",
          "LRA",
          "TRUE PEAK",
          "TARGET",
          "Loudness target preset: -14 (streaming music) / -16 (Apple Music) / -23 (EBU R128 broadcast)",
          "Reset integrated loudness, LRA and true peak hold",
          "MIN",
          "SLOW",
          "MED",
          "FAST",
          "MAX",
          "Analyzer response speed (release time): LOG 4/2/1/0.5/0.2 s for MIN..MAX; LIN ≈ ×1.2 (4.8/2.4/1.2/0.6/0.25 s). Attack fixed 0.05 s. Click cycles slow → fast.",
          "STEREO FIELD",
          "CORRELATION",
          "WIDTH",
          "BALANCE",
          "Anti-Phase",
          "Stereo display range: click to cycle floor -60 / -80 / -100 dB",
      },
      {
          "释放",
          "范围",
          "起音",
          "分辨率",
          "撤销",
          "重做",
          "保存",
          "读取",
          "语言",
          "深色",
          "浅色",
          "主题色",
          "设置",
          "主题",
          "色相",
          "饱和度",
          "无",
          "低",
          "中",
          "高",
          "中文",
          "频谱显示释放时间（对数域回落，0.05–2 秒）",
          "释放回落模式：对数 = dB 域单极点（接近信号时渐缓），线性 = 恒定 dB/s 速率下落",
          "频谱显示范围：点击循环切换底部 80 / 100 / 120 dB",
          "频谱显示上升时间",
          "频谱分析 FFT 尺寸（低/中/高: 2048/4096/8192）",
          "PBT 低频分辨率（低/中/高：40/20/10 Hz，越小越精细）",
          "切换分析引擎（STFT / VQT / PBT / RTA）",
          "音频",
          "输入",
          "输出",
          "驱动",
          "声道显示：PWR（合并，能量和）/ L/R 立体声 / SUM（合并，信号和）",
          "合并算法（PWR: 能量和, SUM: 信号和）",
          "左右",
          "能量和",
          "信号和",
          "对数",
          "线性",
          "保持",
          "重置",
          "电平表模式：dBTP 真峰值（ITU-R BS.1770）/ dBFS+RMS（独立 VU 表常驻显示）",
          "峰值保持开关（频谱保持曲线与电平表保持亮线）",
          "全部重置：电平表保持/过载/持久真峰值与响度（综合、LRA、真峰值）",
          "低",
          "中",
          "高",
          "冻结",
          "冻结显示：定格当前画面；冻结中切换引擎时，用新算法重新分析同一段冻结音频",
          "开发者",
          "测试信号",
          "频率",
          "电平",
          "重开",
          "换种子",
          "送到输出",
          "锁相位",
          "峰值保持时长：点击循环切换 0.5s / 2s / ∞（无限保持）",
          "频谱斜率（dB/oct，支点约 632 Hz）：STFT 0/3/4.5，VQT/PBT/RTA -3/0/1.5；各引擎独立保存",
          "窗函数模式（STFT 与 VQT 独立保存档位）：锐利（Hann: 锐利窄主瓣，经典响应）/ 纯净（5阶 Blackman-Harris: -125 dB 超低旁瓣泄露，主瓣略宽）",
          "锐利",
          "纯净",
          "RTA 分数倍频程分辨率（低/中/高 = 1/6/1/12/1/24：59/118/236 带）",
          "VQT 低频带宽下限 γ（低/中/高 = 20/10/5 Hz）：带宽 = fc/Q + γ —— 高档低频带最窄、最低频分辨力最高；低档低频带更宽、响应更快",
          "瞬时",
          "短时",
          "总响度",
          "LRA",
          "真峰值",
          "目标",
          "响度目标预设：-14（流媒体音乐）/ -16（Apple Music）/ -23（EBU R128 广播）",
          "重置综合响度、LRA 与真峰值锁存",
          "最慢",
          "慢速",
          "中速",
          "快速",
          "最快",
          "频谱响应速度档位（释放时间）：LOG 下 MIN~MAX 为 4/2/1/0.5/0.2 秒；LIN 下约为 ×1.2（4.8/2.4/1.2/0.6/0.25 秒）。上升时间固定 0.05 秒。点击循环：慢 → 快。",
          "声像",
          "相关性",
          "宽度",
          "平衡",
          "反相",
          "声像显示范围：点击循环切换底限 -60 / -80 / -100 dB",
      },
  };
  return kTable[lang][id];
}

} // namespace orm
