#!/usr/bin/env python3
"""gen_sp0256_rom.py — 从 GmEsoft SP0256_CTS256A-AL2 仓库源码生成 SP0256 ROM 数据集头文件。

输入 (从 https://github.com/GmEsoft/SP0256_CTS256A-AL2 拉取, GPL-3.0-or-later):
  SP0256/sp0256_al2.cpp   (AL2 Narrator: 2KB mask ROM + 64 标签 = 5 停顿 + 59 allophone)
  SP0256/sp0256_012.cpp   (012 Intellivoice: 2KB mask ROM + 43 单词标签)
输出: plugins/Narrator/src/dsp/sp0256/Sp0256Roms.h

SP0256 微序控制器按位流取指令; ROM 按 4KB 页组织, allophone/单词码 N 的入口
位于第 1 页偏移 N*2 处 (JMP 到实际微代码)。采样率 = XTAL/312 (默认 3.12MHz = 10kHz)。
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "plugins", "Narrator", "src", "dsp", "sp0256", "Sp0256Roms.h")


def parse_labels(src):
    """GmEsoft 源码: const char * labels[] = { "...", ... };"""
    m = re.search(r"labels\[\s*\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit("labels array not found")
    return re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))


def parse_mask(src):
    """GmEsoft 源码: const uint8_t mask[N] = { 0xE0, ... };"""
    m = re.search(r"const uint8_t mask\[(\d+)\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit("mask array not found")
    vals = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(2))]
    return vals, int(m.group(1))


def c_buf(name, data, per_line=16):
    lines = []
    for i in range(0, len(data), per_line):
        lines.append(", ".join("0x%02X" % b for b in data[i:i + per_line]))
    return "inline const unsigned char %s[%d] = {\n  %s\n};" % (
        name, len(data), ",\n  ".join(lines))


def c_labels(name, labels):
    return "inline const char* const %s[%d] = {\n  %s\n};" % (
        name, len(labels), ", ".join('"%s"' % l for l in labels))


def main():
    if len(sys.argv) != 3:
        print("usage: %s <sp0256_al2.cpp> <sp0256_012.cpp>" % sys.argv[0])
        sys.exit(2)
    al2_src = open(sys.argv[1]).read()
    o12_src = open(sys.argv[2]).read()

    al2_vals, al2_decl = parse_mask(al2_src)
    o12_vals, o12_decl = parse_mask(o12_src)
    if len(al2_vals) != 2048 or len(o12_vals) != 2048:
        raise SystemExit("unexpected ROM byte count (want 2048): %d / %d"
                         % (len(al2_vals), len(o12_vals)))
    # 有效数据后零填充到 4KB 页 (芯片页寻址 12-bit, 越界按 0)
    al2_rom = al2_vals + [0] * (4096 - len(al2_vals))
    o12_rom = o12_vals + [0] * (4096 - len(o12_vals))

    al2_labels = parse_labels(al2_src)
    o12_labels = parse_labels(o12_src)
    if len(al2_labels) != 64:
        raise SystemExit("unexpected AL2 label count: %d" % len(al2_labels))
    if len(o12_labels) != 43:
        raise SystemExit("unexpected 012 label count: %d" % len(o12_labels))

    parts = [
        "// Auto-generated by tools/gen_sp0256_rom.py. Do not edit by hand.",
        "//",
        "// GI/Microchip SP0256 语音 ROM 数据集 (GPL-3.0-or-later, 源: GmEsoft",
        "// SP0256_CTS256A-AL2 逆向工程仓库, 抽取自芯片 mask ROM).",
        "//",
        "// AL2 = Narrator 版: 59 allophone + 5 停顿 (0..63); 012 = Intellivoice 版:",
        "// 43 个单词 (0=FIFO 1..5=停顿 6..42=单词, 见 k012Labels). 标签数组索引即",
        "// 写入芯片 ALD 的代码 (6-bit, 每 ROM 上限 64); 入口微代码在 ROM 偏移 N*2.",
        "// 有效数据 2KB, 零填充到 4KB 页以匹配芯片 12-bit 页寻址.",
        "#pragma once",
        "",
        "namespace orm::sp0256 {",
        "",
        "struct Variant {",
        "  const char* name;              // 短标签 (UI 语音段): AL2 / 012",
        "  const char* const* labels;     // 码 -> 名称 (大小写不敏感匹配)",
        "  int nLabels;                   // 有效标签数 (码上限 63, 超出无效)",
        "  const unsigned char* data;     // 4KB 页 ROM 字节 (N*2 处为入口)",
        "};",
        "",
    ]
    parts.append(c_labels("kAl2Labels", al2_labels))
    parts.append("")
    parts.append(c_labels("k012Labels", o12_labels))
    parts.append("")
    parts.append(c_buf("kRomAl2", al2_rom))
    parts.append("")
    parts.append(c_buf("kRom012", o12_rom))
    parts.append("")
    parts.append("// 版本顺序 = kSp0256Voice 参数枚举 (0=AL2 1=012)")
    parts.append("inline const Variant kVariants[2] = {")
    parts.append('  {"AL2", kAl2Labels, 64, kRomAl2},')
    parts.append('  {"012", k012Labels, 43, kRom012},')
    parts.append("};")
    parts.append("inline constexpr int kNumVariants = 2;")
    parts.append("")
    parts.append("} // namespace orm::sp0256")
    parts.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print("wrote %s  (AL2 %d labels / %d B, 012 %d labels / %d B)"
          % (OUT, len(al2_labels), len(al2_rom), len(o12_labels), len(o12_rom)))


if __name__ == "__main__":
    main()