#!/usr/bin/env python3
"""gen_cts256a_rom.py — 从 GmEsoft CTS256A-AL2 源码生成 CTS256A ROM 数据集头文件。

输入 (https://github.com/GmEsoft/SP0256_CTS256A-AL2, GPL-3.0-or-later):
  CTS256A-AL2/CTS256A_AL2.cpp   (内嵌 CTS256A_AL2_ROM[0x1000])
输出: plugins/Narrator/src/dsp/cts256a/Cts256aRoms.h

CTS256A-AL2 = TMS7000 单片机 + 4KB 掩膜 ROM (0xF000-0xFFFF), ROM 内含
letter-to-sound 规则引擎; 芯片把英文文本转成 SP0256-AL2 allophone 码流。
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "plugins", "Narrator", "src", "dsp", "cts256a", "Cts256aRoms.h")


def main():
    if len(sys.argv) != 2:
        print("usage: %s <CTS256A_AL2.cpp>" % sys.argv[0])
        sys.exit(2)
    src = open(sys.argv[1]).read()
    m = re.search(r"const uchar CTS256A_AL2_ROM\[0x1000\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit("CTS256A_AL2_ROM array not found")
    vals = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(1))]
    if len(vals) != 4096:
        raise SystemExit("unexpected ROM byte count: %d" % len(vals))

    lines = []
    for i in range(0, len(vals), 16):
        lines.append("  %s" % ", ".join("0x%02X" % b for b in vals[i:i + 16]))

    parts = [
        "// Auto-generated by tools/gen_cts256a_rom.py. Do not edit by hand.",
        "//",
        "// GI/Microchip CTS256A-AL2 text-to-speech 控制器掩膜 ROM (4KB, 0xF000-0xFFFF)",
        "// 源: GmEsoft SP0256_CTS256A-AL2 逆向工程仓库 (GPL-3.0-or-later);",
        "// 与 palazzol/TMS7xxx_dumper 的 cts256a.bin 同源。",
        "// ROM 内含 letter-to-sound 规则引擎 + TMS7000 引导代码; 输出为",
        "// SP0256-AL2 allophone 码 (0..63)。",
        "#pragma once",
        "",
        "namespace orm::cts256a {",
        "",
        "inline const unsigned char kRom[4096] = {",
        ",\n".join(lines),
        "};",
        "",
        "} // namespace orm::cts256a",
        "",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print("wrote %s  (%d bytes)" % (OUT, len(vals)))


if __name__ == "__main__":
    main()