#!/usr/bin/env python3
"""gen_s14001_vocab.py — 从 MAME romset 生成 TSI S14001A 语音 ROM 数据集头文件。

输入 (assets/s14001rom/, 用户放置, MAME 驱动核对过 CRC):
  berzerk/berzerk_r_vo_1c.1c + berzerk_r_vo_2c.2c  (4KB, 20kHz)
  flight2k/snd_u9.716                             (2KB, 20kHz)
  csc8/101-32107                                  (4KB, 25kHz)
  csc8/101-64101|64105|64106                      (8KB, 25kHz, A12 bank 分高低半区)
输出: plugins/Narrator/src/dsp/s14001/S14001Roms.h

每个子集 = 一个 12-bit 寻址窗口 (≤4KB) 的语音 ROM; 芯片音高 = clock/128。
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROMDIR = os.path.join(ROOT, "assets", "s14001rom")
OUT = os.path.join(ROOT, "plugins", "Narrator", "src", "dsp", "s14001", "S14001Roms.h")


def read(*parts):
    with open(os.path.join(ROMDIR, *parts), "rb") as f:
        return f.read()


def c_array(name, data, per_line=16):
    lines = []
    for i in range(0, len(data), per_line):
        lines.append(", ".join("0x%02X" % b for b in data[i:i + per_line]))
    return "inline const unsigned char %s[] = {\n  %s\n};" % (name, ",\n  ".join(lines))


def main():
    b1 = read("berzerk", "berzerk_r_vo_1c.1c")
    b2 = read("berzerk", "berzerk_r_vo_2c.2c")
    f2k = read("flight2k", "snd_u9.716")
    c32107 = read("csc8", "101-32107")
    c64101 = read("csc8", "101-64101")
    c64105 = read("csc8", "101-64105")
    c64106 = read("csc8", "101-64106")

    assert len(b1) == 2048 and len(b2) == 2048, "berzerk vo size"
    assert len(f2k) == 2048, "flight2k size"
    assert len(c32107) == 4096, "csc 32107 size"
    for c in (c64101, c64105, c64106):
        assert len(c) == 8192, "csc 8KB size"

    sets = [
        ("kRom_BZK",  b1 + b2, 4096, 20000.0, "Stern Berzerk 街机 (VSU-1000 语音板)"),
        ("kRom_F2K",  f2k,     2048, 20000.0, "Stern Flight 2000 弹球 (MP-200)"),
        ("kRom_C0",   c32107,  4096, 25000.0, "Fidelity CSC 语音棋 BIOS0"),
        ("kRom_C1",   c64101[:4096],  4096, 25000.0, "Fidelity BIOS1 低半区"),
        ("kRom_C2",   c64101[4096:],  4096, 25000.0, "Fidelity BIOS1 高半区"),
        ("kRom_C3",   c64105[:4096],  4096, 25000.0, "Fidelity BIOS2 低半区"),
        ("kRom_C4",   c64105[4096:],  4096, 25000.0, "Fidelity BIOS2 高半区"),
        ("kRom_C5",   c64106[:4096],  4096, 25000.0, "Fidelity BIOS3 低半区"),
        ("kRom_C6",   c64106[4096:],  4096, 25000.0, "Fidelity BIOS3 高半区"),
    ]

    parts = [
        "// Auto-generated by tools/gen_s14001_vocab.py. Do not edit by hand.",
        "//",
        "// TSI/SSi S14001A (1975, 'Custom ROM Controller') 语音 ROM 数据集.",
        "// 数据来源: MAME romsets (街机/玩具固件, 用户授权使用); MAME 模拟代码 BSD-3-Clause.",
        "// 每个子集是一个 12-bit 寻址窗口 (<=4KB) 的语音 ROM 字节; clock 为该机台",
        "// 的原生芯片时钟, 基频 = clock / 128. 子集顺序 = kTsiBank 参数枚举.",
        "#pragma once",
        "",
        "namespace orm::s14001 {",
        "",
        "struct Set {",
        "  const char* name;             // 短标签 (UI 子集段)",
        "  const unsigned char* data;    // ROM 字节",
        "  int len;                      // 有效字节数 (超出返 0)",
        "  double clock;                 // 原生芯片时钟 Hz",
        "};",
        "",
    ]
    names = []
    for name, data, _, _, _ in sets:
        parts.append(c_array(name, data))
        parts.append("")
        names.append(name)

    labels = ["BZ", "F2", "C0", "C1", "C2", "C3", "C4", "C5", "C6"]
    comments = [s[4] for s in sets]
    parts.append("inline const Set kSets[] = {")
    for i, (name, _, length, clock, comment) in enumerate(sets):
        parts.append('  {"%s", %s, %d, %.1f}, // %s' % (labels[i], name, length, clock, comment))
    parts.append("};")
    parts.append("inline constexpr int kNumSets = 9;")
    parts.append("")
    parts.append("} // namespace orm::s14001")
    parts.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    total = sum(len(s[1]) for s in sets)
    print("wrote %s  (%d bytes across %d sets)" % (OUT, total, len(sets)))


if __name__ == "__main__":
    main()